### ISSUE TITLE
OneNote Clipper does not 'remember' the last-used Notebook and always defaults to pages inside the first Notebook

### ISSUE THREAD

**Issue by calydon** [anilkumarum/one-clipper#8]
1. Begin a Clipping Operation by clicking on the pinned OneNote extension.

2. The operation always begins with the first notebook in the notebook list. I'm not sure if this is alphabetical order or OneNote's order. 
 ![Screenshot 2024-12-06 160102](https://github.com/user-attachments/assets/eab6d256-8255-405a-a6d8-41d03d61db46)
Request: have OneClipper begin with the last Notebook used or allow the option for this behaviour. 

3. Navigate to a different notebook. 
![Screenshot 2024-12-06 152103](https://github.com/user-attachments/assets/f8ec1d30-c7e8-4af5-9ef9-cf3555044a5b)

4. Complete the clipping operation by selecting a page within the Notebook and find that the only pages offered are the ones inside the default first notebook. The selection of a different Notebook in step 3, had no effect. 
![Screenshot 2024-12-06 155304](https://github.com/user-attachments/assets/94ed9d58-2886-4979-8dfe-7e150183fa11)
Request: Have OneClipper offer pages to save to from the Notebook selected before clicking 'clip article'.

5. Complete the Clipping operation and then navigate to the default first notebook and find the clipping you just made. Workaround this issue by then moving that clipping to the correct notebook.  
![Screenshot 2024-12-06 152610](https://github.com/user-attachments/assets/6458dca6-7933-4768-a79c-9889b0d3f786)

This is still the best (and only) option for Firefox users who are sticking with OneNote, but the experience could be so much easier.

**Comment by anilkumarum** [comment]
Namaste,

Thank you for reporting the bug and for providing such a detailed explanation. While the issue is complex, the solution is quite simple.

It turns out that I forgot to save the new notebook when switching from the popup window, but I did save it from the side panel. I’ll be updating the extension within the next 2-3 days.

In the meantime, please use the side panel to switch notebooks.

Thank you again, and have a wonderful day!

Best regards,
